---
title: "GM-UAW Cohort Study"
subtitle: "``Weighted'' cumulative incidence"
date: \today
fontsize: 11pt
format:
  pdf:
    documentclass: scrartcl
    geometry: margin=2.4cm, footskip=1cm
header-includes:
- \input{\string~/HeadRs/stathead.sty}
- \usepackage{framed}\renewenvironment{quote}{\colorlet{shadecolor}{orange!15}\begin{snugshade}}{\end{snugshade}}
- \usepackage{enumitem}\setlist[enumerate]{leftmargin=*}
- \usepackage{scrlayer-scrpage} % instead of fancyhdr
- \usepackage{setspace}\onehalfspacing
- \theoremstyle{remark}\newtheorem*{claim}{Claim}
- \allowdisplaybreaks
execute:
  freeze: auto
editor_options: 
  chunk_output_type: inline
bibliography: "`r path.expand('~/Box Sync/papers/EnvEpi.bib')`"
csl: "`r path.expand('~/HeadRs/csl/AMA.csl')`"
---

```{r setup, include=F}
knitr::opts_chunk$set(echo = F,
											warning = F,
											message = F,
											cache = F,
											fig.align = "center",
											fig.pos = "H",
											results = "asis")

library(here); library(tidyverse); library(data.table);
library(lubridate); library(xtable)

source("~/HeadRs/00-my-theme.R")
incidence.key <- fread(here::here("cancer incidence", "cancer-key-expanded.tsv"))

```

1. Use pooled logistic regression to approximate the $J = 2$ subdistribution hazard functions given covariates $W$ and exposure $X$, where $j = 1$ indicates cancer incidence and $j = 2$ indicates natural cause mortality.
$$\begin{aligned}
h_j(t \mid W, X) &= \lim_{\delta \rightarrow 0} \frac{1}{\delta} \Prob{ t < T < t + \delta, J = j \mid (T > T \cup (T < t \cap J \ne j)), W, X }\\
&\approx \Prob{ t < T < t + 1, J = j \mid (T > T \cup (T < t \cap J \ne j)), W, X } \equiv p_j(t \mid W, X)
\end{aligned}$$
For natural cause mortality ($j = 2$), we start follow-up in the minmum of 1941 or three years after hire, including all who were hired after 1938. For cancer incidence $j = 1$, we start follow-up in 1973 (or 1985 if we do not use SEER). There is still censoring form loss to FU and death due to external causes.

2. For each person-year, evaluate $p_j(t \mid W = w, do(X = x))$ where $x$ is the counterfactual exposure level of interest, and $w$ is the observed covariate combination. Set $S_2(t \mid W, do(X = x)) = \prod^t(1 - p_2(t \mid W, do(X = x)))$. See Greenland's paper on model-based standardization.[@Greenland_2004]

3. For each person-year starting in the first year of cancer incidence follow-up, take the product $p_1(t \mid w, do(X = x)) \cdot S_2(t \mid w, do(X = x))$.

4. Take the sum of products $\sum^T_t p_1(t \mid w, do(X = x)) \cdot S_2(t \mid w, do(X = x))$. This is a "weighted" estimate of the cumulative incidence.

5. Estimate cumulative incidence ratios by evaluating the sum in step 4 for different counterfactual levels of exposure $x$.

___